const CFG=window.BEEBIEW_CONFIG||{},LIMIT=CFG.DAILY_LIMIT||2;
const online=CFG.SUPABASE_ANON_KEY&&!CFG.SUPABASE_ANON_KEY.includes('วาง_');
const db=online?supabase.createClient(CFG.SUPABASE_URL,CFG.SUPABASE_ANON_KEY):null;
const KEY='beebiew_bookings_v4',$=(s,p=document)=>p.querySelector(s),$$=(s,p=document)=>[...p.querySelectorAll(s)];
const day=()=>{const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().split('T')[0]};
const local=()=>{try{return JSON.parse(localStorage.getItem(KEY))||[]}catch{return[]}};const save=a=>localStorage.setItem(KEY,JSON.stringify(a));
const fmt=s=>new Intl.DateTimeFormat('th-TH',{dateStyle:'long'}).format(new Date(s+'T00:00:00'));const code=()=>`BB${new Date().toISOString().slice(2,10).replaceAll('-','')}${String(Date.now()).slice(-4)}`;
async function all(){if(db){const {data,error}=await db.from('bookings').select('*').order('created_at',{ascending:false});if(!error)return data||[]}return local()}
async function countDate(d){if(db){const {count,error}=await db.from('bookings').select('*',{count:'exact',head:true}).eq('booking_date',d).neq('status','ปฏิเสธ');if(!error)return count||0}return local().filter(x=>(x.booking_date||x.date)===d&&x.status!=='ปฏิเสธ').length}
async function add(x){if(db){const {error}=await db.from('bookings').insert(x);if(error)throw error}else{const a=local();a.push(x);save(a)}}
async function setState(id,status){if(db){const {error}=await db.from('bookings').update({status}).eq('booking_code',id);if(error)throw error}else{const a=local(),i=a.findIndex(x=>(x.booking_code||x.id)===id);if(i>=0){a[i].status=status;save(a)}}}
async function remove(id){if(db){await db.from('bookings').delete().eq('booking_code',id)}else save(local().filter(x=>(x.booking_code||x.id)!==id))}
function global(){const m=$('#menuToggle'),n=$('#mainNav');if(m)m.onclick=()=>n.classList.toggle('open');const t=$('#themeToggle');if(t)t.onclick=()=>{document.body.classList.toggle('dark');t.textContent=document.body.classList.contains('dark')?'☀️':'🌙'};addEventListener('scroll',()=>{const p=document.documentElement,b=$('#scrollProgress');if(b)b.style.width=(p.scrollTop/(p.scrollHeight-p.clientHeight)*100||0)+'%'});const o=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.1});$$('.reveal').forEach(x=>o.observe(x))}
async function home(){const a=await all(),u=await countDate(day());if($('#todayBooked'))$('#todayBooked').textContent=u;if($('#todayRemaining'))$('#todayRemaining').textContent=Math.max(0,LIMIT-u);if($('#allBookings'))$('#allBookings').textContent=a.length}
function booking(){const f=$('#bookingForm');if(!f)return;const date=$('#bookingDate'),time=$('#bookingTime'),type=$('#bookingType'),cap=$('#capacityMessage');date.min=day();for(let h=9;h<=20;h++){const o=document.createElement('option');o.value=`${String(h).padStart(2,'0')}:00`;o.textContent=o.value;time.appendChild(o)}const cards=$$('#typePicker button');cards.forEach(c=>{const o=document.createElement('option');o.value=c.dataset.type;o.textContent=c.dataset.type;type.appendChild(o);c.onclick=()=>pick(c.dataset.type)});function pick(v){type.value=v;cards.forEach(c=>c.classList.toggle('active',c.dataset.type===v))}type.onchange=()=>pick(type.value);const q=new URLSearchParams(location.search).get('type');if(q)pick(q);async function capacity(){if(!date.value)return cap.textContent='';const u=await countDate(date.value);cap.textContent=u>=LIMIT?'❌ วันนี้คิวเต็มแล้ว กรุณาเลือกวันอื่น':`วันที่เลือกยังเหลือ ${LIMIT-u} คิว`;f.querySelector('[type=submit]').disabled=u>=LIMIT}date.onchange=capacity;let pending;f.onsubmit=async e=>{e.preventDefault();if(await countDate(date.value)>=LIMIT)return capacity();const d=Object.fromEntries(new FormData(f));pending={booking_code:code(),customer_name:d.name,phone:d.phone,booking_date:d.date,booking_time:d.time,booking_type:d.type,location:d.location||'',details:d.details||'',status:'รอยืนยัน'};$('#confirmSummary').innerHTML=`<p><b>ชื่อ:</b> ${pending.customer_name}</p><p><b>วันและเวลา:</b> ${fmt(pending.booking_date)} เวลา ${pending.booking_time}</p><p><b>ประเภท:</b> ${pending.booking_type}</p>`;$('#confirmModal').showModal()};$('#cancelConfirm').onclick=()=>$('#confirmModal').close();$('#confirmSubmit').onclick=async()=>{try{await add(pending);$('#confirmModal').close();$('#successMessage').innerHTML=`รหัสการจองของคุณคือ <strong>${pending.booking_code}</strong><br>กรุณาเก็บรหัสนี้ไว้ตรวจสอบสถานะ`;$('#successModal').showModal();f.reset();pick('');capacity()}catch(e){alert('บันทึกไม่สำเร็จ: '+e.message)}};$('#closeSuccess').onclick=()=>$('#successModal').close()}
function status(){const f=$('#statusForm');if(!f)return;f.onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(f)),a=await all(),b=a.find(x=>(x.booking_code||x.id).toLowerCase()===d.bookingId.trim().toLowerCase()&&x.phone===d.phone.trim());if(!b)return $('#statusResult').innerHTML='<div class="status-card glass"><h3>ไม่พบข้อมูลการจอง</h3></div>';const st=b.status,cls=st==='ยืนยันแล้ว'?'approved':st==='ปฏิเสธ'?'rejected':'pending';$('#statusResult').innerHTML=`<div class="status-card glass"><span class="status-pill ${cls}">${st}</span><h2>${b.booking_code||b.id}</h2><p><b>ชื่อ:</b> ${b.customer_name||b.name}</p><p><b>วันและเวลา:</b> ${fmt(b.booking_date||b.date)} เวลา ${b.booking_time||b.time}</p><p><b>ประเภท:</b> ${b.booking_type||b.type}</p></div>`}}
async function admin(){if(!$('#adminLogin'))return;if(!db){$('#adminLogin').insertAdjacentHTML('beforeend','<p><b>ยังไม่ได้ใส่ Publishable Key ใน config.js</b></p>');return}$('#adminLoginBtn').onclick=async()=>{const {error}=await db.auth.signInWithPassword({email:$('#adminEmail')?.value||prompt('อีเมลแอดมิน'),password:$('#adminPassword')?.value||prompt('รหัสผ่าน')});if(error)return alert(error.message);$('#adminLogin').hidden=true;$('#adminPanel').hidden=false;render()};const {data}=await db.auth.getSession();if(data.session){$('#adminLogin').hidden=true;$('#adminPanel').hidden=false;render()}if($('#adminSearch'))$('#adminSearch').oninput=render;if($('#adminFilter'))$('#adminFilter').onchange=render}
async function render(){const a=await all(),q=($('#adminSearch')?.value||'').toLowerCase(),f=$('#adminFilter')?.value||'';$('#adminTotal').textContent=a.length;$('#adminPending').textContent=a.filter(x=>x.status==='รอยืนยัน').length;$('#adminApproved').textContent=a.filter(x=>x.status==='ยืนยันแล้ว').length;$('#adminRejected').textContent=a.filter(x=>x.status==='ปฏิเสธ').length;const rows=a.filter(x=>(!f||x.status===f)&&(!q||[(x.booking_code||x.id),(x.customer_name||x.name),x.phone,(x.booking_type||x.type)].join(' ').toLowerCase().includes(q)));$('#adminList').innerHTML=rows.length?rows.map(x=>`<article class="admin-card glass"><span class="status-pill ${x.status==='ยืนยันแล้ว'?'approved':x.status==='ปฏิเสธ'?'rejected':'pending'}">${x.status}</span><h3>${x.customer_name||x.name} • ${x.booking_code||x.id}</h3><p>${fmt(x.booking_date||x.date)} เวลา ${x.booking_time||x.time} • ${x.booking_type||x.type}</p><p>📞 ${x.phone}</p><div class="admin-actions"><button class="small-btn approve" onclick="changeStatus('${x.booking_code||x.id}','ยืนยันแล้ว')">ยืนยัน</button><button class="small-btn reject" onclick="changeStatus('${x.booking_code||x.id}','ปฏิเสธ')">ปฏิเสธ</button><button class="small-btn delete" onclick="deleteOne('${x.booking_code||x.id}')">ลบ</button></div></article>`).join(''):'<div class="admin-card glass">ยังไม่มีรายการจอง</div>'}
window.changeStatus=async(id,s)=>{await setState(id,s);render()};window.deleteOne=async id=>{if(confirm('ลบรายการนี้หรือไม่?')){await remove(id);render()}};
document.addEventListener('DOMContentLoaded',()=>{global();const p=document.body.dataset.page;if(p==='home')home();if(p==='booking')booking();if(p==='status')status();if(p==='admin')admin()});
